name: Close old proposals that need more information

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Close old proposals that need more information
        uses: dwieeb/needs-reply@v1
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          issue-label: "needs reply"
          close-message: |
            It looks like this proposal didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

            Have a great day!
            Capacitor Community Bot 💙
